/**
 * Deposits DP10 — Constants & Configuration
 * Table name, column definitions, field sets, and regex patterns.
 */

export const DEPOSITS_DP10_TABLE = "deposits_dp10";

export const DEPOSITS_DP10_COLUMNS = [
    "NUMERO_CONTRATO",
    "FECHA_NEGOCIACION",
    "FECHA_EFECTIVA",
    "CODIGO_OFICINA",
    "NUM_PRODUCTO",
    "NUM_PRODUCTO_LEGADO",
    "NUM_RECIBO_APERTURA",
    "NUM_RECIBO_CANCELACION",
    "ID_GRUPO_PRODUCTO",
    "ID_PRODUCTO",
    "MNEMONIC",
    "ID_CUSTOMER",
    "ID_CUSTOMER_ROLE",
    "MONTO_APERTURA",
    "MONEDA",
    "PLAZO",
    "ID_BASE_TIEMPO",
    "NUM_CERT_FISICO",
    "ID_METODO_FONDEO",
    "COD_VERIFICACION",
    "NUM_CTA_ORIG_LEGADO",
    "NUM_CTA_ORIG",
    "MONTO_ORIG_FONDEO",
    "MONTO_EFEC_FONDEO",
    "TIPO_CHEQUE",
    "MONTO_CHEQ_FONDEO",
    "MONTO_DP_CANCELADO",
    "CTA_BANCO_CENTRAL",
    "TASA_OPERACION",
    "TASA_POOL",
    "FREC_PAGO_INT",
    "TIPO_PAGO_INT",
    "ID_ACERCAMIENTO",
    "FORMA_PAGO_INT",
    "CTA_PAGO_INT_LEGADO",
    "CTA_PAGO_INT",
    "USR_REG_APERTURA",
    "FECHA_REG_APERTURA",
    "USR_APROBO_APERTURA",
    "FECHA_APROBO_APERTURA",
    "OFICIAL_RELACION",
    "ESTADO_PRODUCTO",
    "FECHA_VENCIMIENTO",
    "FECHA_ULT_RENOVACION",
    "FECHA_PROX_RENOVACION",
    "FECHA_PROXIMO_PAGO",
    "FECHA_ULT_MOVIMIENTO",
    "SALDO_CAPITAL_ACTUAL",
    "INTERES_ACUMULADO",
    "INTERES_DEVENGADO",
    "SALDO_CIERRE",
    "TOTAL_EMBARGO_PARCIAL",
    "CTA_INTERNA_FONDEO",
    "CTA_INTERNA_INT_PAGADEROS",
    "ID_MOTIVO_CANCELACION",
    "COMISION_MINIMA",
    "TIENE_SOLICITUD_EXONERACION",
    "USR_SOLICITA_EXONERACION",
    "FECHA_SOLICITUD_EXONERACION",
    "USR_APROBO_EXONERACION",
    "FECHA_APROBO_EXONERACION",
    "ESTADO_SOLICITUD_EXONERACION",
    "COMISION_CALCULADA",
    "COMISION_EXONERADA",
    "COMISION_PAGAR",
    "MONTO_RETEN_IMP_INT",
    "ID_FORMA_PAGO_CANCEL",
    "DESC_FORMA_PAGO_CANCEL",
    "CTA_CANCELACION_LEGADO",
    "CTA_CANCELACION",
    "ID_CANAL_CANCELACION",
    "CTA_CANCEL_CRE_CTA_INTERNA",
    "USR_REG_CANCELACION",
    "USR_APR_CANCELACION",
    "FECHA_REG_CANCELACION",
    "FECHA_APR_CANCELACION",
    "FECHA_CANCELACION",
    "REL_TITULARES",
    "FECHA_ORIG_CONTRATO",
];

export const DEPOSITS_DP10_EXTRA_COLUMNS = [
    "LEGAL_ID",
    "LEGAL_DOC",
    "EXONERATED",
    "USED",
    "TIMES_USED",
];

export const EXTRA_COLUMN_TYPES: Record<string, string> = {
    LEGAL_ID: "TEXT",
    LEGAL_DOC: "TEXT",
    EXONERATED: "BOOLEAN",
    USED: "BOOLEAN DEFAULT 0",
    TIMES_USED: "INTEGER DEFAULT 0",
};

export const DECIMAL_FIELDS = new Set([
    "MONTO_APERTURA",
    "MONTO_ORIG_FONDEO",
    "MONTO_EFEC_FONDEO",
    "MONTO_CHEQ_FONDEO",
    "MONTO_DP_CANCELADO",
    "SALDO_CAPITAL_ACTUAL",
    "INTERES_ACUMULADO",
    "INTERES_DEVENGADO",
    "SALDO_CIERRE",
    "TOTAL_EMBARGO_PARCIAL",
    "COMISION_MINIMA",
    "COMISION_CALCULADA",
    "COMISION_EXONERADA",
    "COMISION_PAGAR",
    "MONTO_RETEN_IMP_INT",
]);

export const RATE_FIELDS = new Set(["TASA_OPERACION", "TASA_POOL"]);

export const DATE_8_FIELDS = new Set([
    "FECHA_EFECTIVA",
    "FECHA_VENCIMIENTO",
    "FECHA_ULT_RENOVACION",
    "FECHA_PROX_RENOVACION",
    "FECHA_PROXIMO_PAGO",
    "FECHA_ULT_MOVIMIENTO",
    "FECHA_CANCELACION",
    "FECHA_ORIG_CONTRATO",
]);

export const DATE_10_FIELDS = new Set([
    "FECHA_NEGOCIACION",
    "FECHA_REG_APERTURA",
    "FECHA_APROBO_APERTURA",
    "FECHA_SOLICITUD_EXONERACION",
    "FECHA_APROBO_EXONERACION",
    "FECHA_REG_CANCELACION",
    "FECHA_APR_CANCELACION",
]);

export const ENUM_FIELDS: Record<string, string[]> = {
    TIENE_SOLICITUD_EXONERACION: ["SI", "NO"],
};

export const DECIMAL_REGEX = /^-?(?:\d+|\d*\.\d+)(?:[eE][+-]?\d+)?$/;
export const DATE_8_REGEX = /^\d{8}$/;
export const DATE_10_REGEX = /^\d{10}$/;
